services:
  network-deploy-service:
    networks:
      -kokorobank
  microservice-base-config:
    extends:
      service: network-deploy-service
    environment:
      SPRING_PROFILES_ACTIVE: default
