services:
  rabbit:
    image: rabbitmq:3.1.2-management
    hostname: rabbitmq
    ports:
      -"5672:5672"
      -"15672:15672"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      -kokorobank:




  account-service:
    image: ebaby1738/account-service:v2
    container_name: account-service-ms
    ports:
      -"8080:8080"
    depends_on:
      -config-server:
         condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -kokorobank
    environment:
      SPRING_APPLICATION_NAME:"account-service"
      SPRING_CONFIG_IMPORT:"configserver:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE:default


  loan-service:
    image: ebaby1738/loan-service:v2
    container_name: loan-service-ms
    ports:
      -"8090:8090"
    depends_on:
      -config-server:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -kokorobank
    environment:
      SPRING_APPLICATION_NAME:"loan-service"
      SPRING_CONFIG_IMPORT:"configserver:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE:default

  card-service:
    image: ebaby1738/card-service:v2
    container_name: card-service-ms
    ports:
      -"9000:9000"
    depends_on:
      -config-server:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -kokorobank
    environment:
      SPRING_APPLICATION_NAME:"account-service"
      SPRING_CONFIG_IMPORT:"configserver:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE:default

  config-server:
    image: ebaby1738/config-server:v2
    container_name: account-service-ms
    ports:
      -"8071:8071"
    depends_on:
      -rabbit:
         condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -kokorobank

networks:
  kokorobank:
    driver:"bridge"
