server:
  port: 8090
spring:
  application:
    name: loans
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/loansDB
    username: root
    password: Mysql8371
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  devtools:
    restart:
      enabled: true
  config:
    import: "optional:configserver:http://localhost:8071/"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  info:
    env:
      enabled: true



eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: "LOANS"
    description: "Kokoro bank loan application"
    version: "1.0.0"


logging:
  level:
    com:
      kokoro:
        loan-service: DEBUG
