services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service



  accountsDB:
    image: mysql
    ports:
      -"3306:3306"
    environment:
      MYSQL_DATABASE:accountsDB
    extends:
      file: commom-config.yml
      service: network-db-service

  loansDB:
    image: mysql
    ports:
      -"3307:3306"
    environment:
      MYSQL_DATABASE:loansDB
    extends:
      file: commom-config.yml
      service: network-db-service


  cardsDB:
    image: mysql
    ports:
      -"3308:3306"
    environment:
      MYSQL_DATABASE:cardsDB
    extends:
      file: commom-config.yml
      service: network-db-service


  account-service:
    image: ebaby1738/account-service:v3
    container_name: account-service-ms
    ports:
      -"8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME:"account-service"
      SPRING_DATASOURCE_URL:"jdbc:mysql://accountsDB:3306/accountsDB"
    depends_on:
      accountsDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config




  loan-service:
    image: ebaby1738/loan-service:v3
    container_name: loan-service-ms
    ports:
      -"8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME:"loan-service"
      SPRING_DATASOURCE_URL:"jdbc:mysql://loansDB:3306/loansDB"
    depends_on:
      loansDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  card-service:
    image: ebaby1738/card-service:v3
    container_name: card-service-ms
    ports:
      -"9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME:"account-service"
      SPRING_DATASOURCE_URL:"jdbc:mysql://loansDB:3306/loansDB"
    depends_on:
      cardsDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  config-server:
    image: ebaby1738/config-server:v3
    container_name: account-service-ms
    ports:
      -"8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  gatewayserver:
    image: "ebaby1738/gateway-server:v3"
    container_name: gateway-server-ms
    ports:
      - "8072:8072"
    depends_on:
      account-service:
        condition: service_healthy
      loan-service:
        condition: service_healthy
      card-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  eureka-server:
    image: ebaby1738/eureka-server:v3
    container_name: eureka-server-ms
    ports:
      -"8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eureka-config

    environment:
      SPRING_APPLICATION_NAME:"eureka-server"

networks:
  kokorobank:
    driver:"bridge"

  #run <mvn compile jib:dockerBuild> in all the 3 irectories of the services ie loan, account, card
  #to generate their docker images
