spring:
  application:
    name: "config-server"
  profiles:
    active: git
  #active: native

  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
        git:
          timeout: 5
          uri: https://github.com/Ebaby1738/micro-service-banking.git
          default-label: main
          clone-on-start: true
          force-pull: true

encrypt:
  #key: ""
server:
  port: 8071
