services:
  accountsDB:
    image: mysql
    ports:
      -"3306:3306"
    environment:
      MYSQL_DATABASE:accountsDB
    extends:
      file: commom-config.yml
      service: network-db-service

  loansDB:
    image: mysql
    ports:
      -"3307:3306"
    environment:
      MYSQL_DATABASE:loansDB
    extends:
      file: commom-config.yml
      service: network-db-service


  cardsDB:
    image: mysql
    ports:
      -"3308:3306"
    environment:
      MYSQL_DATABASE:cardsDB
    extends:
      file: commom-config.yml
      service: network-db-service


  account-service:
    image: ebaby1738/account-service:v2
    container_name: account-service-ms
    ports:
      -"8080:8080"
    environment:
      SPRING_APPLICATION_NAME:"account-service"
      SPRING_DATASOURCE_URL:"jdbc:mysql://accountsDB:3306/accountsDB"
    depends_on:
      accountsDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  loan-service:
    image: ebaby1738/loan-service:v2
    container_name: loan-service-ms
    ports:
      -"8090:8090"
    environment:
      SPRING_APPLICATION_NAME:"loan-service"
      SPRING_DATASOURCE_URL:"jdbc:mysql://loansDB:3306/loansDB"
    depends_on:
      loansDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  card-service:
    image: ebaby1738/card-service:v2
    container_name: card-service-ms
    ports:
      -"9000:9000"
    environment:
      SPRING_APPLICATION_NAME:"account-service"
      SPRING_DATASOURCE_URL:"jdbc:mysql://loansDB:3306/loansDB"
    depends_on:
      cardsDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  config-server:
    image: ebaby1738/config-server:v2
    container_name: account-service-ms
    ports:
      -"8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  kokorobank:
    driver:"bridge"

#run <mvn compile jib:dockerBuild> in all the 3 irectories of the services ie loan, account, card
  #to generate their docker images
