
build:
  version:"2.0"

accounts:
  message: "welcome to Kokoro Bank accounts service related QA Apis"
  contactDetails:
    name: "Ebenezer Irene - Developer"
    email: "ebabytechub@gmail.com"
  onCallSupport:
    -(234)8024978496
    -(234)8024978496

