services:
  network-deploy-service:
    networks:
      -kokorobank


  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:



  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      -config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      SPRING_PROFILES_ACTIVE: qa
